version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: "123"
  quote_consumer:
    build: .
    container_name: quotes_runner
    volumes:
      - ./logs:/app/logs
      - .env.docker:/app/.env.docker
    command: [ "uv", "run", "python", "-m", "crypto_converter.quote_consumer.main", "--env=docker" ]
  converter_api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - .env.docker:/app/.env.docker
    command: [ "uv", "run", "python", "-m", "crypto_converter.api.main", "--host=0.0.0.0", "--port=8000", "--env=docker" ]
