version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: "123"
  quote_consumer:
    build: .
    container_name: quotes_runner
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: [ "uv", "run", "crypto_converter/quote_consumer/main.py", "--env=docker" ]
